ui:
  title: "My TON Status"
  header: "My TON Status"
  logo: "/assets/logo.svg"
  favicon:
    default: "/assets/favicon-32x32.png"
    size16x16: "/assets/favicon-16x16.png"
    size32x32: "/assets/favicon-32x32.png"
  default-sort-by: group
  default-expanded: true
  default-refresh-interval: 60
  hide-controls: true
  footer: "My TON Status"
  buttons:
    - name: "mytonprovider.org"
      link: "https://mytonprovider.org"
    - name: "mytonstorage.org"
      link: "https://mytonstorage.org"
